services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: logforge-frontend-oss
    container_name: ${FRONTEND_SERVICE_CONTAINER_NAME:-logforge-frontend-oss}
    environment:
      # BACKEND_SERVICE_CONTAINER_NAME: "logforge-backend" # This is the default host name for the backend service
      # Change this to the host name you have the backend service running on
      VITE_BACKEND_SERVICE_HOST: "http://${BACKEND_SERVICE_CONTAINER_NAME:-logforge-backend}"
      # VITE_BACKEND_SERVICE_PORT: "8000" # This is the default port for the backend service
      # Change this to the port you have the backend service running on
      VITE_BACKEND_SERVICE_PORT: "${BACKEND_SERVICE_PORT:-8000}"
      VITE_EXPOSED_BACKEND_PORT: "${EXPOSED_BACKEND_PORT:-8000}"
    ports:
      - "${EXPOSED_FRONTEND_PORT:-3000}:${FRONTEND_SERVICE_PORT:-3000}"
