export type ComponentVariant = "filled" | "outline" | "gradient" | "text" | "none";
export type ComponentColors = Colors | "default";
export type ComponentSize = "fit" | "full";

export const componentStretchW: Record<string, string> = {
  fit: "w-fit min-w-[max-content]",
  full: "w-full",
};

export const componentStretchH: Record<string, string> = {
  fit: "h-fit min-h-[max-content]",
  full: "h-full",
};

export const componentPadding: Record<string, string> = {
  "4xs": "p-4xs",
  "3xs": "p-3xs",
  "2xs": "p-2xs",
  xs: "p-xs",
  sm: "p-sm",
  md: "p-md",
  lg: "p-lg",
  xl: "p-xl",
  "2xl": "p-2xl",
  "3xl": "p-3xl",
  "4xl": "p-4xl",
  "4xs-3xs": "p-4xs-3xs",
  "3xs-2xs": "p-3xs-2xs",
  "2xs-xs": "p-2xs-xs",
  "xs-sm": "p-xs-sm",
  "sm-md": "p-sm-md",
  "md-lg": "p-md-lg",
  "lg-xl": "p-lg-xl",
  "xl-2xl": "p-xl-2xl",
  "2xl-3xl": "p-2xl-3xl",
  "3xl-4xl": "p-3xl-4xl",
};

export const componentPaddingX: Record<string, string> = {
  "4xs": "px-4xs",
  "3xs": "px-3xs",
  "2xs": "px-2xs",
  xs: "px-xs",
  sm: "px-sm",
  md: "px-md",
  lg: "px-lg",
  xl: "px-xl",
  "2xl": "px-2xl",
  "3xl": "px-3xl",
  "4xl": "px-4xl",
  "4xs-3xs": "px-4xs-3xs",
  "3xs-2xs": "px-3xs-2xs",
  "2xs-xs": "px-2xs-xs",
  "xs-sm": "px-xs-sm",
  "sm-md": "px-sm-md",
  "md-lg": "px-md-lg",
  "lg-xl": "px-lg-xl",
  "xl-2xl": "px-xl-2xl",
  "2xl-3xl": "px-2xl-3xl",
  "3xl-4xl": "px-3xl-4xl",
};

export const componentPaddingY: Record<string, string> = {
  "4xs": "py-4xs",
  "3xs": "py-3xs",
  "2xs": "py-2xs",
  xs: "py-xs",
  sm: "py-sm",
  md: "py-md",
  lg: "py-lg",
  xl: "py-xl",
  "2xl": "py-2xl",
  "3xl": "py-3xl",
  "4xl": "py-4xl",
  "4xs-3xs": "py-4xs-3xs",
  "3xs-2xs": "py-3xs-2xs",
  "2xs-xs": "py-2xs-xs",
  "xs-sm": "py-xs-sm",
  "sm-md": "py-sm-md",
  "md-lg": "py-md-lg",
  "lg-xl": "py-lg-xl",
  "xl-2xl": "py-xl-2xl",
  "2xl-3xl": "py-2xl-3xl",
  "3xl-4xl": "py-3xl-4xl",
};

export const componentPaddingLeft: Record<string, string> = {
  "4xs": "pl-4xs",
  "3xs": "pl-3xs",
  "2xs": "pl-2xs",
  xs: "pl-xs",
  sm: "pl-sm",
  md: "pl-md",
  lg: "pl-lg",
  xl: "pl-xl",
  "2xl": "pl-2xl",
  "3xl": "pl-3xl",
  "4xl": "pl-4xl",
  "4xs-3xs": "pl-4xs-3xs",
  "3xs-2xs": "pl-3xs-2xs",
  "2xs-xs": "pl-2xs-xs",
  "xs-sm": "pl-xs-sm",
  "sm-md": "pl-sm-md",
  "md-lg": "pl-md-lg",
  "lg-xl": "pl-lg-xl",
  "xl-2xl": "pl-xl-2xl",
  "2xl-3xl": "pl-2xl-3xl",
  "3xl-4xl": "pl-3xl-4xl",
};

export const componentPaddingRight: Record<string, string> = {
  "4xs": "pr-4xs",
  "3xs": "pr-3xs",
  "2xs": "pr-2xs",
  xs: "pr-xs",
  sm: "pr-sm",
  md: "pr-md",
  lg: "pr-lg",
  xl: "pr-xl",
  "2xl": "pr-2xl",
  "3xl": "pr-3xl",
  "4xl": "pr-4xl",
  "4xs-3xs": "pr-4xs-3xs",
  "3xs-2xs": "pr-3xs-2xs",
  "2xs-xs": "pr-2xs-xs",
  "xs-sm": "pr-xs-sm",
  "sm-md": "pr-sm-md",
  "md-lg": "pr-md-lg",
  "lg-xl": "pr-lg-xl",
  "xl-2xl": "pr-xl-2xl",
  "2xl-3xl": "pr-2xl-3xl",
  "3xl-4xl": "pr-3xl-4xl",
};

export const componentPaddingTop: Record<string, string> = {
  "4xs": "pt-4xs",
  "3xs": "pt-3xs",
  "2xs": "pt-2xs",
  xs: "pt-xs",
  sm: "pt-sm",
  md: "pt-md",
  lg: "pt-lg",
  xl: "pt-xl",
  "2xl": "pt-2xl",
  "3xl": "pt-3xl",
  "4xl": "pt-4xl",
  "4xs-3xs": "pt-4xs-3xs",
  "3xs-2xs": "pt-3xs-2xs",
  "2xs-xs": "pt-2xs-xs",
  "xs-sm": "pt-xs-sm",
  "sm-md": "pt-sm-md",
  "md-lg": "pt-md-lg",
  "lg-xl": "pt-lg-xl",
  "xl-2xl": "pt-xl-2xl",
  "2xl-3xl": "pt-2xl-3xl",
  "3xl-4xl": "pt-3xl-4xl",
};

export const componentPaddingBottom: Record<string, string> = {
  "4xs": "pb-4xs",
  "3xs": "pb-3xs",
  "2xs": "pb-2xs",
  xs: "pb-xs",
  sm: "pb-sm",
  md: "pb-md",
  lg: "pb-lg",
  xl: "pb-xl",
  "2xl": "pb-2xl",
  "3xl": "pb-3xl",
  "4xl": "pb-4xl",
  "4xs-3xs": "pb-4xs-3xs",
  "3xs-2xs": "pb-3xs-2xs",
  "2xs-xs": "pb-2xs-xs",
  "xs-sm": "pb-xs-sm",
  "sm-md": "pb-sm-md",
  "md-lg": "pb-md-lg",
  "lg-xl": "pb-lg-xl",
  "xl-2xl": "pb-xl-2xl",
  "2xl-3xl": "pb-2xl-3xl",
  "3xl-4xl": "pb-3xl-4xl",
};

export const componentRadius: Record<string, string> = {
  "4xs": "rounded-(--spacing-4xs)",
  "3xs": "rounded-(--spacing-3xs)",
  "2xs": "rounded-(--spacing-2xs)",
  xs: "rounded-(--spacing-xs)",
  sm: "rounded-(--spacing-sm)",
  md: "rounded-(--spacing-md)",
  lg: "rounded-(--spacing-lg)",
  xl: "rounded-(--spacing-xl)",
  "2xl": "rounded-(--spacing-2xl)",
  "3xl": "rounded-(--spacing-3xl)",
  "4xl": "rounded-(--spacing-4xl)",
  "4xs-3xs": "rounded-(--spacing-4xs-3xs)",
  "3xs-2xs": "rounded-(--spacing-3xs-2xs)",
  "2xs-xs": "rounded-(--spacing-2xs-xs)",
  "xs-sm": "rounded-(--spacing-xs-sm)",
  "sm-md": "rounded-(--spacing-sm-md)",
  "md-lg": "rounded-(--spacing-md-lg)",
  "lg-xl": "rounded-(--spacing-lg-xl)",
  "xl-2xl": "rounded-(--spacing-xl-2xl)",
  "2xl-3xl": "rounded-(--spacing-2xl-3xl)",
  "3xl-4xl": "rounded-(--spacing-3xl-4xl)",
  full: "rounded-full",
};

export const componentRadiusTopLeft: Record<string, string> = {
  "4xs": "rounded-tl-(--spacing-4xs)",
  "3xs": "rounded-tl-(--spacing-3xs)",
  "2xs": "rounded-tl-(--spacing-2xs)",
  xs: "rounded-tl-(--spacing-xs)",
  sm: "rounded-tl-(--spacing-sm)",
  md: "rounded-tl-(--spacing-md)",
  lg: "rounded-tl-(--spacing-lg)",
  xl: "rounded-tl-(--spacing-xl)",
  "2xl": "rounded-tl-(--spacing-2xl)",
  "3xl": "rounded-tl-(--spacing-3xl)",
  "4xl": "rounded-tl-(--spacing-4xl)",
  "4xs-3xs": "rounded-tl-(--spacing-4xs-3xs)",
  "3xs-2xs": "rounded-tl-(--spacing-3xs-2xs)",
  "2xs-xs": "rounded-tl-(--spacing-2xs-xs)",
  "xs-sm": "rounded-tl-(--spacing-xs-sm)",
  "sm-md": "rounded-tl-(--spacing-sm-md)",
  "md-lg": "rounded-tl-(--spacing-md-lg)",
  "lg-xl": "rounded-tl-(--spacing-lg-xl)",
  "xl-2xl": "rounded-tl-(--spacing-xl-2xl)",
  "2xl-3xl": "rounded-tl-(--spacing-2xl-3xl)",
  "3xl-4xl": "rounded-tl-(--spacing-3xl-4xl)",
};

export const componentRadiusTopRight: Record<string, string> = {
  "4xs": "rounded-tr-(--spacing-4xs)",
  "3xs": "rounded-tr-(--spacing-3xs)",
  "2xs": "rounded-tr-(--spacing-2xs)",
  xs: "rounded-tr-(--spacing-xs)",
  sm: "rounded-tr-(--spacing-sm)",
  md: "rounded-tr-(--spacing-md)",
  lg: "rounded-tr-(--spacing-lg)",
  xl: "rounded-tr-(--spacing-xl)",
  "2xl": "rounded-tr-(--spacing-2xl)",
  "3xl": "rounded-tr-(--spacing-3xl)",
  "4xl": "rounded-tr-(--spacing-4xl)",
  "4xs-3xs": "rounded-tr-(--spacing-4xs-3xs)",
  "3xs-2xs": "rounded-tr-(--spacing-3xs-2xs)",
  "2xs-xs": "rounded-tr-(--spacing-2xs-xs)",
  "xs-sm": "rounded-tr-(--spacing-xs-sm)",
  "sm-md": "rounded-tr-(--spacing-sm-md)",
  "md-lg": "rounded-tr-(--spacing-md-lg)",
  "lg-xl": "rounded-tr-(--spacing-lg-xl)",
  "xl-2xl": "rounded-tr-(--spacing-xl-2xl)",
  "2xl-3xl": "rounded-tr-(--spacing-2xl-3xl)",
  "3xl-4xl": "rounded-tr-(--spacing-3xl-4xl)",
};

export const componentRadiusBottomLeft: Record<string, string> = {
  "4xs": "rounded-bl-(--spacing-4xs)",
  "3xs": "rounded-bl-(--spacing-3xs)",
  "2xs": "rounded-bl-(--spacing-2xs)",
  xs: "rounded-bl-(--spacing-xs)",
  sm: "rounded-bl-(--spacing-sm)",
  md: "rounded-bl-(--spacing-md)",
  lg: "rounded-bl-(--spacing-lg)",
  xl: "rounded-bl-(--spacing-xl)",
  "2xl": "rounded-bl-(--spacing-2xl)",
  "3xl": "rounded-bl-(--spacing-3xl)",
  "4xl": "rounded-bl-(--spacing-4xl)",
  "4xs-3xs": "rounded-bl-(--spacing-4xs-3xs)",
  "3xs-2xs": "rounded-bl-(--spacing-3xs-2xs)",
  "2xs-xs": "rounded-bl-(--spacing-2xs-xs)",
  "xs-sm": "rounded-bl-(--spacing-xs-sm)",
  "sm-md": "rounded-bl-(--spacing-sm-md)",
  "md-lg": "rounded-bl-(--spacing-md-lg)",
  "lg-xl": "rounded-bl-(--spacing-lg-xl)",
  "xl-2xl": "rounded-bl-(--spacing-xl-2xl)",
  "2xl-3xl": "rounded-bl-(--spacing-2xl-3xl)",
  "3xl-4xl": "rounded-bl-(--spacing-3xl-4xl)",
};

export const componentRadiusBottomRight: Record<string, string> = {
  "4xs": "rounded-br-(--spacing-4xs)",
  "3xs": "rounded-br-(--spacing-3xs)",
  "2xs": "rounded-br-(--spacing-2xs)",
  xs: "rounded-br-(--spacing-xs)",
  sm: "rounded-br-(--spacing-sm)",
  md: "rounded-br-(--spacing-md)",
  lg: "rounded-br-(--spacing-lg)",
  xl: "rounded-br-(--spacing-xl)",
  "2xl": "rounded-br-(--spacing-2xl)",
  "3xl": "rounded-br-(--spacing-3xl)",
  "4xl": "rounded-br-(--spacing-4xl)",
  "4xs-3xs": "rounded-br-(--spacing-4xs-3xs)",
  "3xs-2xs": "rounded-br-(--spacing-3xs-2xs)",
  "2xs-xs": "rounded-br-(--spacing-2xs-xs)",
  "xs-sm": "rounded-br-(--spacing-xs-sm)",
  "sm-md": "rounded-br-(--spacing-sm-md)",
  "md-lg": "rounded-br-(--spacing-md-lg)",
  "lg-xl": "rounded-br-(--spacing-lg-xl)",
  "xl-2xl": "rounded-br-(--spacing-xl-2xl)",
  "2xl-3xl": "rounded-br-(--spacing-2xl-3xl)",
  "3xl-4xl": "rounded-br-(--spacing-3xl-4xl)",
};

export const componentColors: Record<string, string> = {
  primary: "primary",
  secondary: "secondary",
  accent: "accent",
  background: "background",
  middleground: "middleground",
  foreground: "foreground",
  dividers: "dividers",
  highlight: "highlight",
  error: "error",
  success: "success",
  text: "text",
  "alt-text": "alt-text",
  "muted-text": "muted-text",
  interactive: "interactive",
};

export const componentColorUtils: Record<string, Record<string, string>> = {
  bg80: {
    primary: "bg-primary/80",
    secondary: "bg-secondary/80",
    accent: "bg-accent/80",
    background: "bg-background/80",
    middleground: "bg-middleground/80",
    foreground: "bg-foreground/80",
    dividers: "bg-dividers/80",
    highlight: "bg-highlight/80",
    error: "bg-error/80",
    success: "bg-success/80",
    transparent: "bg-transparent/80",
    text: "bg-text/80",
    "alt-text": "bg-alt-text/80",
    "muted-text": "bg-muted-text/80",
    interactive: "bg-interactive/80",
  },
  bg: {
    primary: "bg-primary/100",
    secondary: "bg-secondary/100",
    accent: "bg-accent/100",
    background: "bg-background/100",
    middleground: "bg-middleground/100",
    foreground: "bg-foreground/100",
    dividers: "bg-dividers/100",
    highlight: "bg-highlight/100",
    error: "bg-error/100",
    success: "bg-success/100",
    text: "bg-text/100",
    "alt-text": "bg-alt-text/100",
    "muted-text": "bg-muted-text/100",
    interactive: "bg-interactive/100",
  },
};

export const componentGap: Record<string, string> = {
  "0": "gap-0",
  "4xs": "gap-4xs",
  "3xs": "gap-3xs",
  "2xs": "gap-2xs",
  xs: "gap-xs",
  sm: "gap-sm",
  md: "gap-md",
  lg: "gap-lg",
  xl: "gap-xl",
  "2xl": "gap-2xl",
  "3xl": "gap-3xl",
  "4xl": "gap-4xl",
  "4xs-3xs": "gap-4xs-3xs",
  "3xs-2xs": "gap-3xs-2xs",
  "2xs-xs": "gap-2xs-xs",
  "xs-sm": "gap-xs-sm",
  "sm-md": "gap-sm-md",
  "md-lg": "gap-md-lg",
  "lg-xl": "gap-lg-xl",
  "xl-2xl": "gap-xl-2xl",
  "2xl-3xl": "gap-2xl-3xl",
  "3xl-4xl": "gap-3xl-4xl",
};

export const componentMargin: Record<string, Record<string, string>> = {
  mt: {
    "0": "mt-0",
    "4xs": "mt-4xs",
    "3xs": "mt-3xs",
    "2xs": "mt-2xs",
    xs: "mt-xs",
    sm: "mt-sm",
    md: "mt-md",
    lg: "mt-lg",
    xl: "mt-xl",
    "2xl": "mt-2xl",
    "3xl": "mt-3xl",
    "4xl": "mt-4xl",
    "4xs-3xs": "mt-4xs-3xs",
    "3xs-2xs": "mt-3xs-2xs",
    "2xs-xs": "mt-2xs-xs",
    "xs-sm": "mt-xs-sm",
    "sm-md": "mt-sm-md",
    "md-lg": "mt-md-lg",
    "lg-xl": "mt-lg-xl",
    "xl-2xl": "mt-xl-2xl",
    "2xl-3xl": "mt-2xl-3xl",
    "3xl-4xl": "mt-3xl-4xl",
  },
  mr: {
    "0": "mr-0",
    "4xs": "mr-4xs",
    "3xs": "mr-3xs",
    "2xs": "mr-2xs",
    xs: "mr-xs",
    sm: "mr-sm",
    md: "mr-md",
    lg: "mr-lg",
    xl: "mr-xl",
    "2xl": "mr-2xl",
    "3xl": "mr-3xl",
    "4xl": "mr-4xl",
    "4xs-3xs": "mr-4xs-3xs",
    "3xs-2xs": "mr-3xs-2xs",
    "2xs-xs": "mr-2xs-xs",
    "xs-sm": "mr-xs-sm",
    "sm-md": "mr-sm-md",
    "md-lg": "mr-md-lg",
    "lg-xl": "mr-lg-xl",
    "xl-2xl": "mr-xl-2xl",
    "2xl-3xl": "mr-2xl-3xl",
    "3xl-4xl": "mr-3xl-4xl",
  },
  ml: {
    "0": "ml-0",
    "4xs": "ml-4xs",
    "3xs": "ml-3xs",
    "2xs": "ml-2xs",
    xs: "ml-xs",
    sm: "ml-sm",
    md: "ml-md",
    lg: "ml-lg",
    xl: "ml-xl",
    "2xl": "ml-2xl",
    "3xl": "ml-3xl",
    "4xl": "ml-4xl",
    "4xs-3xs": "ml-4xs-3xs",
    "3xs-2xs": "ml-3xs-2xs",
    "2xs-xs": "ml-2xs-xs",
    "xs-sm": "ml-xs-sm",
    "sm-md": "ml-sm-md",
    "md-lg": "ml-md-lg",
    "lg-xl": "ml-lg-xl",
    "xl-2xl": "ml-xl-2xl",
    "2xl-3xl": "ml-2xl-3xl",
    "3xl-4xl": "ml-3xl-4xl",
  },
  mb: {
    "0": "mb-0",
    "4xs": "mb-4xs",
    "3xs": "mb-3xs",
    "2xs": "mb-2xs",
    xs: "mb-xs",
    sm: "mb-sm",
    md: "mb-md",
    lg: "mb-lg",
    xl: "mb-xl",
    "2xl": "mb-2xl",
    "3xl": "mb-3xl",
    "4xl": "mb-4xl",
    "4xs-3xs": "mb-4xs-3xs",
    "3xs-2xs": "mb-3xs-2xs",
    "2xs-xs": "mb-2xs-xs",
    "xs-sm": "mb-xs-sm",
    "sm-md": "mb-sm-md",
    "md-lg": "mb-md-lg",
    "lg-xl": "mb-lg-xl",
    "xl-2xl": "mb-xl-2xl",
    "2xl-3xl": "mb-2xl-3xl",
    "3xl-4xl": "mb-3xl-4xl",
  },
};

export const componentFontSize: Record<string, string> = {
  h1: "text-h1",
  h2: "text-h2",
  h3: "text-h3",
  h4: "text-h4",
  h5: "text-h5",
  p: "text-p",
  s: "text-s",
  t: "text-t",
};
